# Generated by Django 3.0.2 on 2021-04-01 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.IntegerField(default=10080)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Expired', 'Expired')], default='Live', max_length=16)),
                ('topic', multiselectfield.db.fields.MultiSelectField(choices=[('Politics', 'Politics'), ('Health', 'Health'), ('Sport', 'Sport'), ('Tech', 'Tech')], max_length=100)),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
